### ISSUE TITLE
Cannot start backend

### ISSUE THREAD

**Issue by throwawaybutton** [MycroftAI/personal-backend#22]
Howdy, I am unable to launch the back end in python 2 or 3.

I have attempted using the specified "personal_backend.conf" and the auto created version, with the same error:

robot@robot-AI:~/personal-backend/examples$ python3 start_backend.py
Traceback (most recent call last):
  File "start_backend.py", line 5, in <module>
    start_backend()
  File "/home/robot/.local/lib/python3.6/site-packages/personal_mycroft_backend/backend/__init__.py", line 70, in start_backend
    app = create_app()
  File "/home/robot/.local/lib/python3.6/site-packages/personal_mycroft_backend/backend/__init__.py", line 41, in create_app
    from personal_mycroft_backend.backend.stt import get_stt_routes
  File "/home/robot/.local/lib/python3.6/site-packages/personal_mycroft_backend/backend/stt.py", line 25, in <module>
    engine = STTFactory.create()
  File "/home/robot/.local/lib/python3.6/site-packages/personal_mycroft_backend/stt/__init__.py", line 228, in create
    return clazz()
  File "/home/robot/.local/lib/python3.6/site-packages/personal_mycroft_backend/stt/__init__.py", line 74, in __init__
    super(GoogleSTT, self).__init__()
  File "/home/robot/.local/lib/python3.6/site-packages/personal_mycroft_backend/stt/__init__.py", line 42, in __init__
    super(TokenSTT, self).__init__()
  File "/home/robot/.local/lib/python3.6/site-packages/personal_mycroft_backend/stt/__init__.py", line 30, in __init__
    self.credential = self.config.get("credential", {})
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by throwawaybutton** [comment]
Disregard, related pull request found.

**Comment by throwawaybutton** [comment]
https://github.com/MycroftAI/personal-backend/pull/20
