### ISSUE TITLE
START

### ISSUE THREAD

**Issue by andresh0816** [MycroftAI/personal-backend#50]
How can i start this backed?

**Comment by el-tocino** [comment]
https://github.com/MycroftAI/personal-backend/blob/master/examples/start_backend.py

**Comment by andresh0816** [comment]
@el-tocino don't work

**Comment by el-tocino** [comment]
Why not?

**Comment by krisgesling** [comment]
Hi Andres,
How did you call `start_backend.py`?
Did you get any specific error messages?

**Comment by andresh0816** [comment]
Yes, i call start_backend.py with python. I get this response:

__name__ == "__main__" no found

in https://github.com/MycroftAI/personal-backend/blob/8a56ae3d767e7dd7664f790c59227de08ca41ec9/examples/start_backend.py#L4

**Comment by el-tocino** [comment]
try copying it to main directory and running it.

**Comment by andresh0816** [comment]
Main directory? Be more especific please

**Comment by krisgesling** [comment]
By main directory I believe he means the top-level directory of the project.

eg if you cloned the project into `~/personal-backend` you could run:
```
cd ~/personal-backend
cp examples/start_backend.py ./
python start_backend.py
```

**Comment by andresh0816** [comment]
```
$ python start_backend.py
Traceback (most recent call last):
  File "start_backend.py", line 5, in <module>
    start_backend()
  File "/home/andres/anaconda3/lib/python3.7/site-packages/personal_mycroft_backend/backend/__init__.py", line 55, in start_backend
    app = create_app()
  File "/home/andres/anaconda3/lib/python3.7/site-packages/personal_mycroft_backend/backend/__init__.py", line 26, in create_app
    from personal_mycroft_backend.backend.stt import get_stt_routes
  File "/home/andres/anaconda3/lib/python3.7/site-packages/personal_mycroft_backend/backend/stt.py", line 11, in <module>
    engine = STTFactory.create()
  File "/home/andres/anaconda3/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 228, in create
    return clazz()
  File "/home/andres/anaconda3/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 74, in __init__
    super(GoogleSTT, self).__init__()
  File "/home/andres/anaconda3/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 42, in __init__
    super(TokenSTT, self).__init__()
  File "/home/andres/anaconda3/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 30, in __init__
    self.credential = self.config.get("credential", {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by krisgesling** [comment]
Have you installed the python dependencies? Personally I prefer this in a venv

```
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```

**Comment by krisgesling** [comment]
You will also need to configure the server as outlined here: 
https://github.com/MycroftAI/personal-backend#install

**Comment by andresh0816** [comment]
```
$python start_backend.py
Traceback (most recent call last):
  File "start_backend.py", line 1, in <module>
    from personal_mycroft_backend.backend import start_backend
ModuleNotFoundError: No module named 'personal_mycroft_backend'

```

**Comment by andresh0816** [comment]
I run that with virtualenv

**Comment by andresh0816** [comment]
(env) andres@Napoleon:~/Documentos/Proyectos/web_api/examples$ python start_backend.py
Traceback (most recent call last):
  File "start_backend.py", line 5, in <module>
    start_backend()
  File "/home/andres/Documentos/Proyectos/web_api/env/lib/python3.7/site-packages/personal_mycroft_backend/backend/__init__.py", line 55, in start_backend
    app = create_app()
  File "/home/andres/Documentos/Proyectos/web_api/env/lib/python3.7/site-packages/personal_mycroft_backend/backend/__init__.py", line 26, in create_app
    from personal_mycroft_backend.backend.stt import get_stt_routes
  File "/home/andres/Documentos/Proyectos/web_api/env/lib/python3.7/site-packages/personal_mycroft_backend/backend/stt.py", line 11, in <module>
    engine = STTFactory.create()
  File "/home/andres/Documentos/Proyectos/web_api/env/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 228, in create
    return clazz()
  File "/home/andres/Documentos/Proyectos/web_api/env/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 74, in __init__
    super(GoogleSTT, self).__init__()
  File "/home/andres/Documentos/Proyectos/web_api/env/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 42, in __init__
    super(TokenSTT, self).__init__()
  File "/home/andres/Documentos/Proyectos/web_api/env/lib/python3.7/site-packages/personal_mycroft_backend/stt/__init__.py", line 30, in __init__
    self.credential = self.config.get("credential", {})
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by krisgesling** [comment]
Are you running that from within the examples directory? 

Probably need to copy `start_backend.py` to `/home/andres/Documentos/Proyectos/web_api/` and run it from there.

**Comment by andresh0816** [comment]
I get this:

```
:~/Documentos/Proyectos/web_api$ python start_backend.py
Traceback (most recent call last):
  File "start_backend.py", line 5, in <module>
    start_backend()
  File "/home/andres/Documentos/Proyectos/web_api/personal_mycroft_backend/backend/__init__.py", line 55, in start_backend
    app = create_app()
  File "/home/andres/Documentos/Proyectos/web_api/personal_mycroft_backend/backend/__init__.py", line 26, in create_app
    from personal_mycroft_backend.backend.stt import get_stt_routes
  File "/home/andres/Documentos/Proyectos/web_api/personal_mycroft_backend/backend/stt.py", line 11, in <module>
    engine = STTFactory.create()
  File "/home/andres/Documentos/Proyectos/web_api/personal_mycroft_backend/stt/__init__.py", line 228, in create
    return clazz()
  File "/home/andres/Documentos/Proyectos/web_api/personal_mycroft_backend/stt/__init__.py", line 74, in __init__
    super(GoogleSTT, self).__init__()
  File "/home/andres/Documentos/Proyectos/web_api/personal_mycroft_backend/stt/__init__.py", line 42, in __init__
    super(TokenSTT, self).__init__()
  File "/home/andres/Documentos/Proyectos/web_api/personal_mycroft_backend/stt/__init__.py", line 30, in __init__
    self.credential = self.config.get("credential", {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by krisgesling** [comment]
Looks like #52 fixes this also

**Comment by krisgesling** [comment]
Just saw in chat that you got this working which is great.

Closing this ticket
